# Auto-generated related-guides mapping for game-guide.club
# Page path -> [(href, anchor text), ...]
RELATED_GUIDES = {
    '7-days-to-die/': [
        ('7-days-to-die/beginners-guide/', "Beginner's Guide"),
        ('7-days-to-die/base-building/', 'Base Building'),
        ('7-days-to-die/weapons-database/', 'Weapons & Tools Database'),
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
    ],
    '7-days-to-die/base-building/': [
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('7-days-to-die/beginners-guide/', "Beginner's Guide"),
        ('7-days-to-die/weapons-database/', 'Weapons & Tools Database'),
        ('7-days-to-die/loot-progression/', 'Loot Stage & Progression'),
    ],
    '7-days-to-die/beginners-guide/': [
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('7-days-to-die/base-building/', 'Base Building'),
        ('7-days-to-die/weapons-database/', 'Weapons & Tools Database'),
        ('7-days-to-die/loot-progression/', 'Loot Stage & Progression'),
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
    ],
    '7-days-to-die/loot-progression/': [
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('7-days-to-die/beginners-guide/', "Beginner's Guide"),
        ('7-days-to-die/base-building/', 'Base Building'),
        ('7-days-to-die/weapons-database/', 'Weapons & Tools Database'),
    ],
    '7-days-to-die/weapons-database/': [
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('7-days-to-die/beginners-guide/', "Beginner's Guide"),
        ('7-days-to-die/base-building/', 'Base Building'),
        ('7-days-to-die/loot-progression/', 'Loot Stage & Progression'),
    ],
    'project-zomboid/': [
        ('project-zomboid/beginners-guide/', "Beginner's Guide"),
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('valheim/', 'Valheim Guide Hub'),
        ('sons-forest/', 'Sons of the Forest Guide Hub'),
    ],
    'project-zomboid/beginners-guide/': [
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
        ('7-days-to-die/', '7 Days to Die Guide Hub'),
        ('7-days-to-die/beginners-guide/', "7 Days to Die Beginner's Guide"),
        ('valheim/', 'Valheim Guide Hub'),
        ('sons-forest/', 'Sons of the Forest Guide Hub'),
    ],
    'core-keeper/': [
        ('core-keeper/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/biomes/', 'Biomes Guide'),
        ('core-keeper/boss-fights/', 'Boss Fights'),
    ],
    'core-keeper/beginners-guide/': [
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('core-keeper/biomes/', 'Biomes Guide'),
        ('core-keeper/boss-fights/', 'Boss Fights'),
        ('core-keeper/equipment-database/', 'Equipment Database'),
    ],
    'core-keeper/biomes/': [
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('core-keeper/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/boss-fights/', 'Boss Fights'),
        ('core-keeper/equipment-database/', 'Equipment Database'),
    ],
    'core-keeper/boss-fights/': [
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('core-keeper/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/biomes/', 'Biomes Guide'),
        ('core-keeper/equipment-database/', 'Equipment Database'),
    ],
    'core-keeper/equipment-database/': [
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('core-keeper/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/biomes/', 'Biomes Guide'),
        ('core-keeper/boss-fights/', 'Boss Fights'),
    ],
    'core-keeper/items-database/': [
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('core-keeper/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/biomes/', 'Biomes Guide'),
        ('core-keeper/boss-fights/', 'Boss Fights'),
    ],
    'crimson-desert/': [
        ('crimson-desert/beginners-guide/', "Beginner's Guide"),
    ],
    'crimson-desert/beginners-guide/': [
        ('crimson-desert/', 'Crimson Desert Guide Hub'),
    ],
    'dst/': [
        ('dst/beginners-guide/', "Beginner's Guide"),
        ('dst/characters/', 'Character Guide'),
        ('dst/base-building/', 'Base Building'),
    ],
    'dst/base-building/': [
        ('dst/', "Don't Starve Together Guide Hub"),
        ('dst/beginners-guide/', "Beginner's Guide"),
        ('dst/characters/', 'Character Guide'),
        ('dst/farming/', 'Farming'),
    ],
    'dst/beginners-guide/': [
        ('dst/', "Don't Starve Together Guide Hub"),
        ('dst/characters/', 'Character Guide'),
        ('dst/base-building/', 'Base Building'),
        ('dst/farming/', 'Farming'),
    ],
    'dst/boss-fights/': [
        ('dst/', "Don't Starve Together Guide Hub"),
        ('dst/beginners-guide/', "Beginner's Guide"),
        ('dst/characters/', 'Character Guide'),
        ('dst/base-building/', 'Base Building'),
    ],
    'dst/characters/': [
        ('dst/', "Don't Starve Together Guide Hub"),
        ('dst/beginners-guide/', "Beginner's Guide"),
        ('dst/base-building/', 'Base Building'),
        ('dst/farming/', 'Farming'),
    ],
    'dst/farming/': [
        ('dst/', "Don't Starve Together Guide Hub"),
        ('dst/beginners-guide/', "Beginner's Guide"),
        ('dst/characters/', 'Character Guide'),
        ('dst/base-building/', 'Base Building'),
    ],
    'dyson/': [
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
    ],
    'dyson/beginners-guide/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
        ('dyson/sphere-design/', 'Sphere Design'),
    ],
    'dyson/combat/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
    ],
    'dyson/dark-fog/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
    ],
    'dyson/logistics/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/sphere-design/', 'Sphere Design'),
    ],
    'dyson/production/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/logistics/', 'Logistics'),
        ('dyson/sphere-design/', 'Sphere Design'),
    ],
    'dyson/resources/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
    ],
    'dyson/sphere-design/': [
        ('dyson/', 'Dyson Sphere Program Complete Guide — Factory Game Guides'),
        ('dyson/beginners-guide/', "Beginner's Guide"),
        ('dyson/production/', 'Production Chains'),
        ('dyson/logistics/', 'Logistics'),
    ],
    'enshrouded/': [
        ('enshrouded/bosses/', 'Boss & Elite Guide'),
        ('enshrouded/weapons/', 'Weapons Database'),
        ('enshrouded/armor/', 'Armor & Gear'),
    ],
    'enshrouded/armor/': [
        ('enshrouded/', 'Enshrouded Guide — Tips, Crafting, Base Building & Boss Strategies'),
        ('enshrouded/bosses/', 'Boss & Elite Guide'),
        ('enshrouded/weapons/', 'Weapons Database'),
        ('enshrouded/building/', 'Building & Base'),
    ],
    'enshrouded/bosses/': [
        ('enshrouded/', 'Enshrouded Guide — Tips, Crafting, Base Building & Boss Strategies'),
        ('enshrouded/weapons/', 'Weapons Database'),
        ('enshrouded/armor/', 'Armor & Gear'),
        ('enshrouded/building/', 'Building & Base'),
    ],
    'enshrouded/building/': [
        ('enshrouded/', 'Enshrouded Guide — Tips, Crafting, Base Building & Boss Strategies'),
        ('enshrouded/bosses/', 'Boss & Elite Guide'),
        ('enshrouded/weapons/', 'Weapons Database'),
        ('enshrouded/armor/', 'Armor & Gear'),
    ],
    'enshrouded/map-exploration/': [
        ('enshrouded/', 'Enshrouded Guide — Tips, Crafting, Base Building & Boss Strategies'),
        ('enshrouded/bosses/', 'Boss & Elite Guide'),
        ('enshrouded/weapons/', 'Weapons Database'),
        ('enshrouded/armor/', 'Armor & Gear'),
    ],
    'enshrouded/weapons/': [
        ('enshrouded/', 'Enshrouded Guide — Tips, Crafting, Base Building & Boss Strategies'),
        ('enshrouded/bosses/', 'Boss & Elite Guide'),
        ('enshrouded/armor/', 'Armor & Gear'),
        ('enshrouded/building/', 'Building & Base'),
    ],
    'factorio/': [
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/beginners-tips/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/blueprint-book/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/circuits/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/strategies/', 'Strategies'),
    ],
    'factorio/defense-guide/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/mods/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/production-ratios/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
        ('factorio/strategies/', 'Strategies'),
    ],
    'factorio/rail-system/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/circuits/', 'Circuit Networks'),
        ('factorio/strategies/', 'Strategies'),
    ],
    'factorio/space-age/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'factorio/strategies/': [
        ('factorio/', 'Factorio Complete Guide — Factory Game Guides'),
        ('factorio/production-ratios/', 'Production Ratios'),
        ('factorio/rail-system/', 'Rail System'),
        ('factorio/circuits/', 'Circuit Networks'),
    ],
    'fire-phoenix/': [
        ('fire-phoenix/beginner-strategy-guide/', 'Beginner Strategy Guide'),
    ],
    'fire-phoenix/beginner-strategy-guide/': [
        ('fire-phoenix/', 'Three Kingdoms: Fire Phoenix Guide Hub'),
    ],
    'games/comparison/': [
        ('games/survival-tiers/', 'Survival Tier List'),
    ],
    'games/survival-tiers/': [
        ('games/comparison/', 'Game Comparison'),
    ],
    'grounded/': [
        ('grounded/creatures/', 'Creature & Bosses'),
        ('grounded/base-building/', 'Base Building'),
        ('grounded/equipment-guide/', 'Equipment Guide'),
    ],
    'grounded/base-building/': [
        ('grounded/', 'Grounded'),
        ('grounded/creatures/', 'Creature & Bosses'),
        ('grounded/equipment-guide/', 'Equipment Guide'),
        ('grounded/story-walkthrough/', 'Story Walkthrough'),
    ],
    'grounded/creatures/': [
        ('grounded/', 'Grounded'),
        ('grounded/base-building/', 'Base Building'),
        ('grounded/equipment-guide/', 'Equipment Guide'),
        ('grounded/story-walkthrough/', 'Story Walkthrough'),
    ],
    'grounded/equipment-guide/': [
        ('grounded/', 'Grounded'),
        ('grounded/creatures/', 'Creature & Bosses'),
        ('grounded/base-building/', 'Base Building'),
        ('grounded/story-walkthrough/', 'Story Walkthrough'),
    ],
    'grounded/story-walkthrough/': [
        ('grounded/', 'Grounded'),
        ('grounded/creatures/', 'Creature & Bosses'),
        ('grounded/base-building/', 'Base Building'),
        ('grounded/equipment-guide/', 'Equipment Guide'),
    ],
    'guides/best-gaming-gear/': [
        ('guides/gaming-setup/', 'Gaming Setup Guide'),
    ],
    'guides/gaming-setup/': [
        ('guides/best-gaming-gear/', 'Gaming Gear'),
    ],
    'manor-lords/': [
        ('manor-lords/beginners-guide/', "Beginner's Guide"),
    ],
    'manor-lords/beginners-guide/': [
        ('manor-lords/', 'Manor Lords Guide — Beginner Tips, Build Order & 0.8 Update Notes'),
    ],
    'minecraft/': [
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
    ],
    'minecraft/beginners-guide/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
        ('minecraft/farming/', 'Farming Guide'),
    ],
    'minecraft/building-tips/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/redstone/', 'Redstone Guide'),
        ('minecraft/farming/', 'Farming Guide'),
    ],
    'minecraft/combat-guide/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
    ],
    'minecraft/enchanting/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
    ],
    'minecraft/endgame/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
    ],
    'minecraft/farming/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/redstone/', 'Redstone Guide'),
    ],
    'minecraft/redstone/': [
        ('minecraft/', 'Minecraft Guide Hub'),
        ('minecraft/beginners-guide/', "Beginner's Guide"),
        ('minecraft/building-tips/', 'Building Tips'),
        ('minecraft/farming/', 'Farming Guide'),
    ],
    'moonlight-peaks/': [
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/mining-caves/', 'Mining & Cave of Echoes'),
    ],
    'moonlight-peaks/beginners-guide/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/fishing-foraging/', 'Fishing & Foraging'),
        ('moonlight-peaks/mining-caves/', 'Mining & Cave of Echoes'),
    ],
    'moonlight-peaks/cooking-recipes/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
    ],
    'moonlight-peaks/crops-farming/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/fishing-foraging/', 'Fishing & Foraging'),
        ('moonlight-peaks/mining-caves/', 'Mining & Cave of Echoes'),
    ],
    'moonlight-peaks/festivals-events/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
    ],
    'moonlight-peaks/fishing-foraging/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/mining-caves/', 'Mining & Cave of Echoes'),
    ],
    'moonlight-peaks/money-making/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
    ],
    'moonlight-peaks/museum-nokturna/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
    ],
    'moonlight-peaks/npc-social/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
    ],
    'moonlight-peaks/tools-upgrades/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/mining-caves/', 'Mining & Cave of Echoes'),
    ],
    'moonlight-peaks/vampire-powers/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/fishing-foraging/', 'Fishing & Foraging'),
    ],
    'moonlight-peaks/mining-caves/': [
        ('moonlight-peaks/', '《月光岭物语》(Moonlight Peaks) 完全攻略指南'),
        ('moonlight-peaks/beginners-guide/', "Beginner's Guide"),
        ('moonlight-peaks/crops-farming/', 'Crop & Farming Guide'),
        ('moonlight-peaks/vampire-powers/', 'Vampire Powers & Spells'),
        ('moonlight-peaks/fishing-foraging/', 'Fishing & Foraging'),
        ('moonlight-peaks/tools-upgrades/', 'Tool Upgrade Guide'),
    ],
    'news/': [
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-05-enshrouded-horizons-update/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
        ('news/posts/2026-07-05-valheim-bog-witch-update/', "Valheim Bog Witch Update: A Complete Guide to the Swamp's New Merchant"),
    ],
    'news/posts/2026-07-05-factorio-space-age-retrospective/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
        ('news/posts/2026-07-05-valheim-bog-witch-update/', "Valheim Bog Witch Update: A Complete Guide to the Swamp's New Merchant"),
    ],
    'news/posts/2026-07-05-satisfactory-1-0-meta/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-valheim-bog-witch-update/', "Valheim Bog Witch Update: A Complete Guide to the Swamp's New Merchant"),
    ],
    'news/posts/2026-07-05-valheim-bog-witch-update/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-06-satisfactory-1-1-patch/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-06-valheim-deep-north/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-07-7d2d-alpha-22/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-08-core-keeper-music-update/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-09-dst-hallowed-nights/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-10-dyson-combat-overhaul/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-11-grounded-2-tease/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-12-minecraft-snapshot-1-22/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-13-palworld-sakurajima-dlc/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-14-rust-july-wipe-changes/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-15-shapez2-content-update/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-16-sons-forest-patch/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-17-stardew-1-7-update/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-18-subnautica-2-announcement/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-07-19-timberborn-update-7/': [
        ('news/', 'News & Updates'),
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
        ('news/posts/2026-07-05-enshrouded-horizons-update/', 'Enshrouded Horizons: Where the Game Stands in Mid-2026'),
        ('news/posts/2026-07-05-factorio-space-age-retrospective/', 'Factorio Space Age: Six Months Later — A Retrospective'),
        ('news/posts/2026-07-05-satisfactory-1-0-meta/', 'Satisfactory 1.0 Meta Changes: How the Factory Game Evolved'),
    ],
    'news/posts/2026-08-03-necesse-rust-romance-update/': [
        ('news/', 'News & Updates'),
        ('necesse/', 'Necesse Guide Hub'),
        ('necesse/beginners-guide/', "Necesse Beginner's Guide"),
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('news/posts/2026-07-07-7d2d-alpha-22/', '7 Days to Die: Alpha 22 Update'),
        ('news/posts/2026-07-06-valheim-deep-north/', 'Valheim: Deep North Biome'),
    ],
    'necesse/': [
        ('necesse/beginners-guide/', "Beginner's Guide"),
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
    ],
    'necesse/beginners-guide/': [
        ('necesse/', 'Necesse Guide Hub'),
        ('news/posts/2026-08-03-necesse-rust-romance-update/', 'Necesse Rust & Romance Update: Scrapyard Incursion & Romance Quests'),
        ('core-keeper/', 'Core Keeper Guide Hub'),
    ],
    'terraria/': [
        ('terraria/beginners-guide/', "Beginner's Guide"),
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('necesse/', 'Necesse Guide Hub'),
    ],
    'terraria/beginners-guide/': [
        ('terraria/', 'Terraria Guide Hub'),
        ('core-keeper/', 'Core Keeper Guide Hub'),
        ('necesse/', 'Necesse Guide Hub'),
        ('minecraft/', 'Minecraft Guide Hub'),
    ],
    'palworld/': [
        ('palworld/beginners-guide/', "Beginner's Guide"),
        ('palworld/1.0-guide/', '1.0 Update Guide'),
        ('palworld/base-building/', 'Base Building'),
    ],
    'palworld/1.0-guide/': [
        ('palworld/', 'Palworld Guide Hub'),
        ('palworld/beginners-guide/', "Beginner's Guide"),
        ('palworld/base-building/', 'Base Building'),
        ('palworld/breeding/', 'Breeding Guide'),
    ],
    'palworld/base-building/': [
        ('palworld/', 'Palworld Guide Hub'),
        ('palworld/beginners-guide/', "Beginner's Guide"),
        ('palworld/1.0-guide/', '1.0 Update Guide'),
        ('palworld/breeding/', 'Breeding Guide'),
    ],
    'palworld/beginners-guide/': [
        ('palworld/', 'Palworld Guide Hub'),
        ('palworld/1.0-guide/', '1.0 Update Guide'),
        ('palworld/base-building/', 'Base Building'),
        ('palworld/breeding/', 'Breeding Guide'),
    ],
    'palworld/breeding/': [
        ('palworld/', 'Palworld Guide Hub'),
        ('palworld/beginners-guide/', "Beginner's Guide"),
        ('palworld/1.0-guide/', '1.0 Update Guide'),
        ('palworld/base-building/', 'Base Building'),
    ],
    'palworld/pals-database/': [
        ('palworld/', 'Palworld Guide Hub'),
        ('palworld/beginners-guide/', "Beginner's Guide"),
        ('palworld/1.0-guide/', '1.0 Update Guide'),
        ('palworld/base-building/', 'Base Building'),
    ],
    'raft/': [
        ('raft/beginners-guide/', "Beginner's Guide"),
        ('raft/items-database/', 'Items & Resources Database'),
        ('raft/islands-database/', 'Islands Database'),
    ],
    'raft/beginners-guide/': [
        ('raft/', 'Raft Guide Hub'),
        ('raft/items-database/', 'Items & Resources Database'),
        ('raft/islands-database/', 'Islands Database'),
        ('raft/cooking-recipes/', 'Cooking Recipes & Food Guide'),
    ],
    'raft/cooking-recipes/': [
        ('raft/', 'Raft Guide Hub'),
        ('raft/beginners-guide/', "Beginner's Guide"),
        ('raft/items-database/', 'Items & Resources Database'),
        ('raft/islands-database/', 'Islands Database'),
    ],
    'raft/islands-database/': [
        ('raft/', 'Raft Guide Hub'),
        ('raft/beginners-guide/', "Beginner's Guide"),
        ('raft/items-database/', 'Items & Resources Database'),
        ('raft/cooking-recipes/', 'Cooking Recipes & Food Guide'),
    ],
    'raft/items-database/': [
        ('raft/', 'Raft Guide Hub'),
        ('raft/beginners-guide/', "Beginner's Guide"),
        ('raft/islands-database/', 'Islands Database'),
        ('raft/cooking-recipes/', 'Cooking Recipes & Food Guide'),
    ],
    'rust/': [
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/base-building/', 'Base Building'),
        ('rust/monuments/', 'Monuments'),
    ],
    'rust/base-building/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/monuments/', 'Monuments'),
        ('rust/farming/', 'Farming'),
    ],
    'rust/beginners-guide/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/base-building/', 'Base Building'),
        ('rust/monuments/', 'Monuments'),
        ('rust/farming/', 'Farming'),
    ],
    'rust/farming/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/base-building/', 'Base Building'),
        ('rust/monuments/', 'Monuments'),
    ],
    'rust/monuments/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/base-building/', 'Base Building'),
        ('rust/farming/', 'Farming'),
    ],
    'rust/pvp-guide/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/base-building/', 'Base Building'),
        ('rust/monuments/', 'Monuments'),
    ],
    'rust/raid-guide/': [
        ('rust/', 'Rust Guide Hub'),
        ('rust/beginners-guide/', "Beginner's Guide"),
        ('rust/base-building/', 'Base Building'),
        ('rust/monuments/', 'Monuments'),
    ],
    'satisfactory/': [
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/alternate-recipes/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/beginners-tips/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/blueprints/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/building/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/lines/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
        ('satisfactory/resources/', 'Resources'),
    ],
    'satisfactory/logistics/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/parts/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/power/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/resources/', 'Resources'),
    ],
    'satisfactory/resources/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'satisfactory/tiers/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/power/', 'Power Systems'),
        ('satisfactory/resources/', 'Resources'),
    ],
    'satisfactory/trains/': [
        ('satisfactory/', 'Satisfactory — Game Overview'),
        ('satisfactory/lines/', 'Production Lines'),
        ('satisfactory/tiers/', 'Tier Progression'),
        ('satisfactory/power/', 'Power Systems'),
    ],
    'shapez2/': [
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
    ],
    'shapez2/buildings/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
    ],
    'shapez2/colors/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
        ('shapez2/shapes/', '⬠ Shapes Reference'),
    ],
    'shapez2/logic/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
    ],
    'shapez2/milestones/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
        ('shapez2/shapes/', '⬠ Shapes Reference'),
    ],
    'shapez2/optimization/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
    ],
    'shapez2/shapes/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/stamps/', 'Stamps & Blueprints'),
    ],
    'shapez2/stamps/': [
        ('shapez2/', 'Shapez 2 Complete Guide — Factory Game Guides'),
        ('shapez2/colors/', 'Color Mixing'),
        ('shapez2/milestones/', 'Milestones'),
        ('shapez2/shapes/', '⬠ Shapes Reference'),
    ],
    'sons-forest/': [
        ('sons-forest/caves-walkthrough/', 'Caves & Walkthrough'),
        ('sons-forest/items-weapons/', 'Items & Weapons'),
        ('sons-forest/crafting/', 'Crafting & Building'),
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
    ],
    'sons-forest/caves-walkthrough/': [
        ('sons-forest/', 'Sons of the Forest'),
        ('sons-forest/items-weapons/', 'Items & Weapons'),
        ('sons-forest/crafting/', 'Crafting & Building'),
        ('sons-forest/endgame-guide/', 'Endgame Guide'),
    ],
    'sons-forest/crafting/': [
        ('sons-forest/', 'Sons of the Forest'),
        ('sons-forest/caves-walkthrough/', 'Caves & Walkthrough'),
        ('sons-forest/items-weapons/', 'Items & Weapons'),
        ('sons-forest/endgame-guide/', 'Endgame Guide'),
    ],
    'sons-forest/endgame-guide/': [
        ('sons-forest/', 'Sons of the Forest'),
        ('sons-forest/caves-walkthrough/', 'Caves & Walkthrough'),
        ('sons-forest/items-weapons/', 'Items & Weapons'),
        ('sons-forest/crafting/', 'Crafting & Building'),
    ],
    'sons-forest/items-weapons/': [
        ('sons-forest/', 'Sons of the Forest'),
        ('sons-forest/caves-walkthrough/', 'Caves & Walkthrough'),
        ('sons-forest/crafting/', 'Crafting & Building'),
        ('sons-forest/endgame-guide/', 'Endgame Guide'),
    ],
    'sons-forest/survival-tips/': [
        ('sons-forest/', 'Sons of the Forest'),
        ('sons-forest/caves-walkthrough/', 'Caves & Walkthrough'),
        ('sons-forest/items-weapons/', 'Items & Weapons'),
        ('sons-forest/crafting/', 'Crafting & Building'),
    ],
    'stardew-valley/': [
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/fishing/', 'Fishing Guide'),
    ],
    'stardew-valley/beginners-guide/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/fishing/', 'Fishing Guide'),
        ('stardew-valley/mining/', 'Mining Guide'),
    ],
    'stardew-valley/farming/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/fishing/', 'Fishing Guide'),
        ('stardew-valley/mining/', 'Mining Guide'),
    ],
    'stardew-valley/fishing/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/mining/', 'Mining Guide'),
    ],
    'stardew-valley/mining/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/fishing/', 'Fishing Guide'),
    ],
    'stardew-valley/money-making/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/fishing/', 'Fishing Guide'),
    ],
    'stardew-valley/relationships/': [
        ('stardew-valley/', 'Stardew Valley Guide Hub'),
        ('stardew-valley/beginners-guide/', "Beginner's Guide"),
        ('stardew-valley/farming/', 'Farming Guide'),
        ('stardew-valley/fishing/', 'Fishing Guide'),
    ],
    'sts2/beginners-guide/': [
        ('sts2/major-update-2-guide/', 'Major Update 2 Guide'),
        ('sts2/v0.108.0-update/', 'V0.108.0 Update'),
        ('sts2/v0.109.0-update/', 'V0.109.0 Update'),
    ],
    'sts2/major-update-2-guide/': [
        ('sts2/beginners-guide/', 'Beginners Guide'),
        ('sts2/v0.108.0-update/', 'V0.108.0 Update'),
        ('sts2/v0.109.0-update/', 'V0.109.0 Update'),
    ],
    'sts2/v0.108.0-update/': [
        ('sts2/beginners-guide/', 'Beginners Guide'),
        ('sts2/major-update-2-guide/', 'Major Update 2 Guide'),
        ('sts2/v0.109.0-update/', 'V0.109.0 Update'),
    ],
    'sts2/v0.109.0-update/': [
        ('sts2/beginners-guide/', 'Beginners Guide'),
        ('sts2/major-update-2-guide/', 'Major Update 2 Guide'),
        ('sts2/v0.108.0-update/', 'V0.108.0 Update'),
    ],
    'starrupture/': [
        ('starrupture/beginners-guide/', "Beginner's Guide"),
        ('satisfactory/', 'Satisfactory Guide Hub'),
        ('factorio/', 'Factorio Guide Hub'),
    ],
    'starrupture/beginners-guide/': [
        ('starrupture/', 'StarRupture Guide Hub'),
        ('satisfactory/', 'Satisfactory Guide Hub'),
        ('factorio/', 'Factorio Guide Hub'),
        ('subnautica/', 'Subnautica Guide Hub'),
    ],
    'subnautica/': [
        ('subnautica/beginners-guide/', "Beginner's Guide"),
        ('subnautica/biomes/', 'Biomes Guide'),
        ('subnautica/creatures-database/', 'Creature Database'),
    ],
    'subnautica/beginners-guide/': [
        ('subnautica/', 'Subnautica Guide Hub'),
        ('subnautica/biomes/', 'Biomes Guide'),
        ('subnautica/creatures-database/', 'Creature Database'),
        ('subnautica/vehicles/', 'Vehicles Guide'),
    ],
    'subnautica/biomes/': [
        ('subnautica/', 'Subnautica Guide Hub'),
        ('subnautica/beginners-guide/', "Beginner's Guide"),
        ('subnautica/creatures-database/', 'Creature Database'),
        ('subnautica/vehicles/', 'Vehicles Guide'),
    ],
    'subnautica/creatures-database/': [
        ('subnautica/', 'Subnautica Guide Hub'),
        ('subnautica/beginners-guide/', "Beginner's Guide"),
        ('subnautica/biomes/', 'Biomes Guide'),
        ('subnautica/vehicles/', 'Vehicles Guide'),
    ],
    'subnautica/resources/': [
        ('subnautica/', 'Subnautica Guide Hub'),
        ('subnautica/beginners-guide/', "Beginner's Guide"),
        ('subnautica/biomes/', 'Biomes Guide'),
        ('subnautica/creatures-database/', 'Creature Database'),
    ],
    'subnautica/vehicles/': [
        ('subnautica/', 'Subnautica Guide Hub'),
        ('subnautica/beginners-guide/', "Beginner's Guide"),
        ('subnautica/biomes/', 'Biomes Guide'),
        ('subnautica/creatures-database/', 'Creature Database'),
    ],
    'sunflower-land/': [
        ('sunflower-land/saltwort-crop-week/', 'Saltwort Crop Week Guide'),
    ],
    'sunflower-land/saltwort-crop-week/': [
        ('sunflower-land/', 'Sunflower Land 攻略'),
    ],
    'timberborn/': [
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/beavers/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/buildings/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/districts/', 'Districts'),
    ],
    'timberborn/districts/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/drought/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/endgame/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/food/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/buildings/', 'Buildings'),
        ('timberborn/districts/', 'Districts'),
    ],
    'timberborn/materials/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/water/', 'Water Management'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
    ],
    'timberborn/water/': [
        ('timberborn/', 'Timberborn Complete Guide — Factory Game Guides'),
        ('timberborn/food/', 'Food & Farming'),
        ('timberborn/buildings/', 'Buildings'),
        ('timberborn/districts/', 'Districts'),
    ],
    'tools/': [
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/boss-tracker/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/card-database/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/crafting-calculator/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/factory-planner/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/game-map/', 'Game Map Reference'),
    ],
    'tools/game-map/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/power-planner/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/factory-planner/', 'Factory Planner'),
        ('tools/game-map/', 'Game Map Reference'),
    ],
    'tools/production-calculator/': [
        ('tools/', 'Interactive Tools'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
        ('tools/game-map/', 'Game Map Reference'),
    ],
    'tools/sts2-build-calculator/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'tools/update-tracker/': [
        ('tools/', 'Interactive Tools'),
        ('tools/production-calculator/', 'Production Ratio Calculator'),
        ('tools/power-planner/', 'Power Grid Planner'),
        ('tools/factory-planner/', 'Factory Planner'),
    ],
    'torchlight-infinite/': [
        ('torchlight-infinite/ss13-cyclone-strike-alchemist/', 'Alchemist Cyclone Strike SS13'),
    ],
    'torchlight-infinite/ss13-cyclone-strike-alchemist/': [
        ('torchlight-infinite/', 'Torchlight Infinite'),
    ],
    'valheim/': [
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
        ('valheim/deep-north-guide/', 'Deep North Guide'),
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
    ],
    'valheim/beginners-guide/': [
        ('valheim/', 'Valheim Guide Hub'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/base-building/', 'Base Building'),
        ('valheim/equipment/', 'Equipment & Food'),
        ('valheim/deep-north-guide/', 'Deep North Guide'),
        ('project-zomboid/', 'Project Zomboid Guide Hub'),
    ],
    'valheim/base-building/': [
        ('valheim/', 'Valheim'),
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/biomes/': [
        ('valheim/', 'Valheim'),
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
        ('valheim/base-building/', 'Base Building'),
        ('valheim/deep-north-guide/', 'Deep North Guide'),
    ],
    'valheim/boss-strategies/': [
        ('valheim/', 'Valheim'),
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/equipment/', 'Equipment & Food'),
        ('valheim/base-building/', 'Base Building'),
        ('valheim/deep-north-guide/', 'Deep North Guide'),
    ],
    'valheim/building-aesthetics/': [
        ('valheim/', 'Valheim'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/cooking-recipes/': [
        ('valheim/', 'Valheim'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/equipment/': [
        ('valheim/', 'Valheim'),
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/base-building/', 'Base Building'),
        ('valheim/deep-north-guide/', 'Deep North Guide'),
    ],
    'valheim/farming-food/': [
        ('valheim/', 'Valheim'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/materials/': [
        ('valheim/', 'Valheim'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/sailing/': [
        ('valheim/', 'Valheim'),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'valheim/deep-north-guide/': [
        ('valheim/', 'Valheim'),
        ('valheim/beginners-guide/', "Beginner's Guide"),
        ('valheim/biomes/', 'Biome Guide'),
        ('valheim/boss-strategies/', 'Boss Strategies'),
        ('valheim/equipment/', 'Equipment & Food'),
    ],
    'vrising/': [
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
    ],
    'vrising/beginners-guide/': [
        ('vrising/', 'V Rising'),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
        ('vrising/materials/', 'Materials & Resources'),
    ],
    'vrising/castle-building/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/materials/', 'Materials & Resources'),
    ],
    'vrising/equipment-upgrade/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
    ],
    'vrising/materials/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
    ],
    'vrising/pvp-strategies/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
    ],
    'vrising/redeem-codes/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/v-blood-carriers/', 'V Blood Carriers'),
        ('vrising/castle-building/', 'Castle Building'),
    ],
    'vrising/v-blood-carriers/': [
        ('vrising/', 'V Rising'),
        ('vrising/beginners-guide/', "Beginner's Guide"),
        ('vrising/castle-building/', 'Castle Building'),
        ('vrising/materials/', 'Materials & Resources'),
    ],
}